### ISSUE TITLE
APIResponseError: API token is invalid

### ISSUE THREAD

**Issue by spacepioneer777** [paperboi/kindle2notion#81] opened 2022-08-29 06:46 UTC
Hi, this is most probably not a bug, but and issue between chair and keyboard:)
I'm not a developer, so intalling Kindle2Notion wasn't an easy task, but I managed it. But when I tried to export the clippings from kindle to Notion by running the Kindle2Notion package, i'm getting error
`notion_client.errors.APIResponseError: API token is invalid`
It seems like a least expected problem, because I simply go to Notion's 'Setting & Members' > Integrations and copy Internal Integration token. Don't understand what could be an issue here. I tried to reinstall the package, but didn't help. Any advice will be highly appreciated! Thanks!

**Comment by ishehraj** [comment] 2022-09-05 23:51
facing the same error :(

**Comment by paperboi** [comment] 2022-10-30 06:33
Hi @spacepioneer777 and @ishehraj ! I just took a look at this and like David mentioned, it's most likely an issue with the Notion API not recognising your integration token for some reason. I'd recommend you try duplicating the K2N Notion template once again to your workspace and create another integration token to use with it, Please let me know if the issue persists. I couldn't reproduce the issue from my end. I hope this helps! I am closing this issue for now.

**Closed by paperboi** 2022-10-30 06:33 UTC
