### ISSUE TITLE
I keep getting this error "raise HTTPError( requests.exceptions.HTTPError: Something went wrong."

### ISSUE THREAD

**Issue by lertsoft** [paperboi/kindle2notion#71] opened 2022-05-27 16:19 UTC
I have been running with this issue after first getting following the steps shown on this <a href=https://github.com/paperboi/kindle2notion/issues/14 >pinned issue </a>. 

The database does not update on notion nor does it show if there has been any activity... any help is appreciated

<img width="819" alt="Screen Shot 2022-05-27 at 12 00 09 PM" src="https://user-images.githubusercontent.com/28693094/170736939-80f9a0da-ef92-447e-a7c2-68a93e2341b2.png">

**Comment by paperboi** [comment] 2022-07-14 19:15
Duplicate of #66 

This is a delayed update but if you're still considering, please update to the latest version of this package and try again.

**Closed by paperboi** 2022-07-14 19:15 UTC
